title: SnackSquad
description: Profiles, Projects, and Interests for the UH Community
google_analytics:
show_downloads: false
theme: jekyll-theme-Midnight
github:
  is_project_page: true
  repository_url: https://github.com/bowfolios/bowfolios
gems:
  - jekyll-mentions
